services:
  socket-server:
    build:
      context: .
      dockerfile: socket-server/Dockerfile
    ports:
      - "81:3001"

  solana-games:
    build:
      context: .
      dockerfile: solana-games/Dockerfile
    ports: 
      - "80:3000"
    environment:
      - NEXT_PUBLIC_SOCKET_URL=ws://57.154.188.238:81
    depends_on:
      - socket-server
