services:
  socket-server:
    build:
      context: .
      dockerfile: socket-server/Dockerfile
    ports:
      - "81:3001"

  solana-games:
    build:
      context: .
      dockerfile: solana-games/Dockerfile
    ports: 
      - "80:3000"
    depends_on:
      - socket-server
